export const USER_CHANGE_TEXT = "USER_CHANGE_TEXT";
export const USER_FETCHED = "USER_FETCHED";
export const USER_ERROR = "USER_ERROR";
export const USER_AUTHENTICATED = "USER_AUTHENTICATED";
export const CLEAR_USER_ERROR = "CLEAR_USER_ERROR";
export const AUTH_USER_STARTED = "AUTH_USER_STARTED";
export const RESET_REDUX = "RESET_REDUX";